on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      matrix:
        version: ["1_24", "1_25", "1_26", "1_27", "1_28"]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build kubectl
        run: nix build .#kubectl_${{ matrix.version }}
