on:
  pull_request:
  push:
    branches: [master]

jobs:
  get-versions:
    name: Get versions to build
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.set-matrix.outputs.test }}
    steps:
      - uses: actions/checkout@main
      - id: set-matrix
        run: |
          VERSIONS=$(jq --compact-output keys < versions.json)
          echo ${VERSIONS}
          echo "test=${VERSIONS}" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: get-versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build kubectl
        run: nix build .#${{ matrix.version }}
